### ISSUE TITLE
Why use Foundation_Tools?

### ISSUE THREAD

**Issue by LucGosso** [episerver/Foundation#190]
Hi all! Thanks for a nice installation procedure, worked really well! (build.cmd)

On /setup , you have option catalogue "Foundation_Tools" - so it installed some products but meny links and branding site was still Mosey fashion retail. 

Q1: Would it not better to not display Foundation_Tools in Setup? 
Q2: Now i istalled both  Foundation_Tools and  Foundation_Fashion, can i remove the commerce database and restart the build.cmd? 

Thank you for puting this in the documentation, would be great!

Regards Luc

**Comment by lunchin** [comment]
We are creating a site to go with the catalog but is not done yet.  The idea was to decouple the sites and catalogs because you might not need to import any catalogs for a cms demo for instance.  The idea  is to have more sites as well like financial services, etc.

Should we update this issue to update the documentation on importing content?

**Comment by LucGosso** [comment]
Good idea, Yes update the documentation on importing content. Even a road map for site and what other part exists when importing. 

Whats the idea behind the locations and tags? 

Just figuring out the site and how to use it (and later will use it as demo for a marketplace partner)

**Comment by lunchin** [comment]
Locations and tags show how to do geo location searches using find as well as improve long-tail traffic with automatic landing pages
