### ISSUE TITLE
Package references question

### ISSUE THREAD

**Issue by ThomasSchmidt** [episerver/Foundation#800]
Looking at the package references of Foundation.csproj it seems it is referencing packages like we did back in the day, explicitly referencing packages instead of using only references to top level packages:

```
<PackageReference Include="EPiServer.Commerce" Version="14.2.1" />
<PackageReference Include="EPiServer.CMS" Version="12.4.0" />
<PackageReference Include="EPiServer.CMS.AspNetCore.HtmlHelpers" Version="12.5.0" />
<PackageReference Include="EPiServer.CMS.Core" Version="12.5.0" />
<PackageReference Include="EPiServer.CMS.UI" Version="12.4.0" />
<PackageReference Include="EPiServer.CMS.UI.Core" Version="12.4.0" />
```
		
I would expect it to be only referencing the top level package and let it pull in its dependencies like this, which is the recommended way in .net core unless you need very specific versions, so it should look as simple as this:
`<PackageReference Include="EPiServer.Commerce" Version="14.2.1" />`

Is there a specific reason for this? Maybe bugfixes for CMS parts when commerce is not updated yet or? is this the recommended approach from Optimizely generally?

Bonus questions: 
csproj file seems like it needs a lot of cleanup with lots of the following in it:
```
<Content Remove="Infrastructure\Social\**" />
<EmbeddedResource Remove="Features\Blocks\CommentsBlock\**" />
<Compile Remove="Features\Blog\BlogCommentBlock\**" />
```

is this some cleanup leftover when upgrading from .net framework to .net 5/6?

**Comment by lunchin** [comment]
You are correct we could just use the top level commerce package and we will probably later but for now we want to make sure the latest version for each package since there are a lot of new features and bug fixes in these early versions.

Second question the social packages are being tested now and then we can uncomment those.  Same with powerslice and geta categories.  We did remove some stuff that is no longer relevant but stuff awaiting packages was commented out on purpose.
